8361288: Fix build of JTReg: wget exited with exit code 4

diff --git a/.github/actions/build-jtreg/action.yml b/.github/actions/build-jtreg/action.yml
--- a/.github/actions/build-jtreg/action.yml
+++ b/.github/actions/build-jtreg/action.yml
@@ -53,7 +53,14 @@ runs:
     - name: 'Build JTReg'
       run: |
         # Build JTReg and move files to the proper locations
-        bash make/build.sh --jdk "$JAVA_HOME_17_X64"
+        retry=0
+        while ! bash make/build.sh --jdk "$JAVA_HOME_17_X64"; do
+          retry=$[$retry+1]
+          if [ $retry -gt 20 ];then
+            echo >&2 "JTReg is failing to build"
+            exit 1
+          fi
+        done
         mkdir ../installed
         mv build/images/jtreg/* ../installed
       working-directory: jtreg/src
